services:
  postgres:
    container_name: documento_postgres_${POSTGRES_DB}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - documento_postgres_data:/data/postgres
    ports:
      - "${POSTGRES_PORT}"
    networks:
      - documento_network
    restart: unless-stopped

networks:
  documento_network:
    name: documento_network_${POSTGRES_DB}
    driver: bridge

volumes:
  documento_postgres_data:
    name: documento_postgres_${POSTGRES_DB}
